#!/bin/sh

  . "$(dirname "$0")/_/husky.sh"

echo "husky > starting pre-commit hook"
echo "husky > running the eslint..."
npm run lint ||
{
  echo
  echo "husky > pre-commit hook failed (try using the 'npm run lint:fix' command)"
  exit 1
}

npm run test ||
{
  echo
  echo "husky > pre-commit hook failed on tests"
  exit 1
}
